sudo: false
language: node_js
node_js:
  - "stable"

before_script:
  - sleep 15
  - mongo mydb_test --eval 'db.addUser("travis", "test");'

services: mongodb

after_success: npm run coveralls:report
